# Generated by Django 5.2.2 on 2025-08-22 15:22

import django.core.validators
import django.db.models.deletion
import larp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BgStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=10, message="C'est le numéro de la question, il doit être compris entre 0 et 10"), django.core.validators.MinValueValidator(limit_value=0, message="C'est le numéro de la question, il doit être compris entre 0 et 10")])),
                ('short_name', models.CharField(max_length=20, verbose_name='Nom (court)')),
                ('question', models.TextField()),
            ],
            options={
                'verbose_name': 'Question background',
                'verbose_name_plural': 'Questions de background',
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Nom')),
                ('form', models.JSONField(default=dict, verbose_name='Formulaire PNJ')),
            ],
            options={
                'verbose_name': 'Opus',
            },
        ),
        migrations.CreateModel(
            name='PnjInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_orga', models.TextField(blank=True, default='')),
                ('prefered_time', models.CharField(choices=[('EARLY', 'Première tâche 6h30'), ('LATE', 'Dernière tâche entre 23h et 2h')], default=[larp.models.PnjInfos.TIME_PREFERENCE['EARLY'], larp.models.PnjInfos.TIME_PREFERENCE['LATE']], max_length=10)),
                ('nigth_action', models.BooleanField(verbose_name='Action de nuit')),
                ('logistic_or_role', models.IntegerField(choices=[('ZERO', 0), ('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5)])),
                ('importance', models.IntegerField(choices=[('ZERO', 0), ('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5)])),
                ('talent', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Infos PNJ',
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BgChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, verbose_name='Nom (court)')),
                ('text', models.TextField(default='', null=True)),
                ('empty', models.BooleanField(default=False, verbose_name='A remplir par le joueur')),
                ('bg_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larp.bgstep', verbose_name='Question background')),
            ],
            options={
                'verbose_name': 'Choix de background',
                'verbose_name_plural': 'Choix de background',
            },
        ),
        migrations.CreateModel(
            name='Character_Bg_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_text', models.TextField(blank=True, default='')),
                ('step', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=10, message="C'est le numéro de la question, il doit être compris entre 0 et 10"), django.core.validators.MinValueValidator(limit_value=0, message="C'est le numéro de la question, il doit être compris entre 0 et 10")])),
                ('bgchoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larp.bgchoice')),
            ],
            options={
                'verbose_name': 'Choix background des perso',
                'verbose_name_plural': 'Choix background des perso',
            },
        ),
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Nom')),
                ('orga_contact', models.TextField(blank=True, default='', verbose_name='Info de contact orga')),
                ('orga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faction',
            },
        ),
        migrations.AddField(
            model_name='bgstep',
            name='faction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larp.faction'),
        ),
        migrations.CreateModel(
            name='Larp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Nom')),
                ('description', models.TextField(blank=True, default='')),
                ('factions_name', models.CharField(max_length=35, verbose_name='Dénomination des groupes (Faction, Gang...)')),
                ('orga_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'GN',
            },
        ),
        migrations.AddField(
            model_name='faction',
            name='larp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='larp.larp', verbose_name='GN'),
        ),
        migrations.CreateModel(
            name='Opus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='Nom')),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.TextField(blank=True, verbose_name='Lieu')),
                ('larp', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='larp.larp')),
            ],
            options={
                'verbose_name_plural': 'Opus',
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('PJ', 'Joueur'), ('PNJV', 'PNJ volant'), ('PNJF', 'PNJ de faction')], default='PJ', max_length=15, verbose_name='Type (PJ, PNJ...)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('opus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larp.opus', verbose_name='Opus')),
            ],
            options={
                'verbose_name': 'Inscription',
            },
        ),
        migrations.CreateModel(
            name='PjInfos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Nom du personnage')),
                ('skills', models.TextField(verbose_name='Compétences')),
                ('last_learned', models.CharField(max_length=60, verbose_name='Compétence apprise lors du dernier opus')),
                ('emotions', models.CharField(choices=[('SOFT', 'Soft, je veux un jeu doux'), ('MOD_POSITIF', 'Modéré Positif, je suis ok pour vivre des événements heureux'), ('MOD_ALL', 'Modéré toutes émotions'), ('SURPRISE', 'Surprenez-moi, vous avez carte blanche'), ('INTENSE', 'Intense, je suis motivé.e pour du drama')], default=[larp.models.PjInfos.EMOTION_PREFERENCE['SOFT']], max_length=25)),
                ('objectives', models.TextField(verbose_name='Objectifs de jeu')),
                ('bg_choices', models.ManyToManyField(blank=True, through='larp.Character_Bg_choices', to='larp.bgchoice')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='larp.faction')),
            ],
            options={
                'verbose_name': 'Infos PJ',
            },
        ),
        migrations.AddField(
            model_name='character_bg_choices',
            name='pjInfos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='larp.pjinfos'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('PJ', 'Joueur'), ('PNJV', 'PNJ volant'), ('PNJF', 'PNJ de faction')], max_length=15, verbose_name='Type (PJ, PNJ...)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pj_infos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='larp.pjinfos')),
                ('pnj_infos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='larp.pnjinfos')),
            ],
            options={
                'verbose_name': 'Fiche perso',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=1.0, verbose_name='Prix')),
                ('access_type', models.CharField(choices=[('PJ', 'Joueur'), ('PNJV', 'PNJ volant'), ('PNJF', 'PNJ de faction')], max_length=15, verbose_name='Type (PJ, PNJ...)')),
                ('opus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='larp.opus', verbose_name='Opus')),
            ],
            options={
                'verbose_name': 'Billet',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prénom :')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nom :')),
                ('pseudos', models.TextField(verbose_name='Pseudos sur les réseaux sociaux :')),
                ('birthdate', models.DateField(verbose_name='Date de naissance :')),
                ('food', models.TextField(blank=True, default='', verbose_name='Régime alimentaire')),
                ('xp_gn', models.CharField(choices=[('ONE', 'Je suis un débutant'), ('TWO', '1 à 2 GNs, je découvre encore'), ('THREE', '3 à 5 GNs, je suis un habitué maintenant'), ('FOUR', '5+ GNs, je vis pour le GN désormais')], default=[larp.models.Profile.XP_GN['ONE']], max_length=10)),
                ('unwanted_people', models.TextField(blank=True, default='', verbose_name='Des gens avec qui vous ne souhaitez pas jouer')),
                ('fears', models.TextField(blank=True, default='', verbose_name='Phobies')),
                ('emergency_contact', models.TextField(default='', verbose_name="Contacts d'urgence")),
                ('activated', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('triggers', models.ManyToManyField(blank=True, to='larp.trigger')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
            },
        ),
        migrations.AddConstraint(
            model_name='bgchoice',
            constraint=models.UniqueConstraint(fields=('short_name', 'bg_step'), name='unique_choice_per_step'),
        ),
        migrations.AddConstraint(
            model_name='bgstep',
            constraint=models.UniqueConstraint(fields=('step', 'faction'), name='unique_bg_step_per_faction'),
        ),
        migrations.AddConstraint(
            model_name='inscription',
            constraint=models.UniqueConstraint(fields=('user', 'opus'), name='unique_inscription'),
        ),
        migrations.AddConstraint(
            model_name='character_bg_choices',
            constraint=models.UniqueConstraint(fields=('pjInfos', 'step'), name='unique_bg_choice_per_charac'),
        ),
    ]
