# Generated by Django 5.2.2 on 2025-08-24 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='pj_infos',
        ),
        migrations.RemoveField(
            model_name='character',
            name='pnj_infos',
        ),
        migrations.RemoveField(
            model_name='character',
            name='user',
        ),
        migrations.DeleteModel(
            name='FormTemplate',
        ),
        migrations.AddField(
            model_name='pjinfos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pnjinfos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='Date de naissance :'),
        ),
        migrations.DeleteModel(
            name='Character',
        ),
    ]
