# Generated by Django 5.2.2 on 2025-09-09 13:32

import django.db.models.deletion
import django.utils.timezone
import larp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0002_remove_character_pj_infos_remove_character_pnj_infos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pjinfos',
            name='larp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='larp.larp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pnjinfos',
            name='larp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='larp.larp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='xp_gn',
            field=models.CharField(choices=[('ONE', 'Je suis un débutant'), ('TWO', '1 à 2 GNs, je découvre encore'), ('THREE', '3 à 5 GNs, je suis un habitué maintenant'), ('FOUR', '5+ GNs, je vis pour le GN désormais')], default=larp.models.Profile.XP_GN['ONE'], max_length=10),
        ),
    ]
