# Generated by Django 5.2.2 on 2025-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0003_inscription_created_at_pjinfos_larp_pnjinfos_larp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnjinfos',
            name='importance',
            field=models.IntegerField(choices=[('ZERO', 0), ('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5)], null=True),
        ),
        migrations.AlterField(
            model_name='pnjinfos',
            name='logistic_or_role',
            field=models.IntegerField(choices=[('ZERO', 0), ('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5)], null=True),
        ),
        migrations.AlterField(
            model_name='pnjinfos',
            name='nigth_action',
            field=models.BooleanField(null=True, verbose_name='Action de nuit'),
        ),
        migrations.AlterField(
            model_name='pnjinfos',
            name='prefered_time',
            field=models.CharField(choices=[('EARLY', 'Première tâche 6h30'), ('LATE', 'Dernière tâche entre 23h et 2h')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pnjinfos',
            name='talent',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
