# Generated by Django 5.2.2 on 2025-09-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0004_alter_pnjinfos_importance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnjinfos',
            name='importance',
            field=models.CharField(choices=[('ZERO', 0), ('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5)], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='pnjinfos',
            name='logistic_or_role',
            field=models.CharField(choices=[('ZERO', 0), ('ONE', 1), ('TWO', 2), ('THREE', 3), ('FOUR', 4), ('FIVE', 5)], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='pnjinfos',
            name='prefered_time',
            field=models.CharField(choices=[('EARLY', 'Première tâche 6h30'), ('LATE', 'Dernière tâche entre 23h et 2h')], default='', max_length=10, null=True),
        ),
    ]
