# Generated by Django 5.2.2 on 2025-09-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0005_alter_pnjinfos_importance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pnjinfos',
            name='prefered_time',
            field=models.CharField(choices=[('EARLY', 'Première tâche 6h30'), ('LATE', 'Dernière tâche entre 23h et 2h'), ('ANY', 'Sans préférence')], default='', max_length=10, null=True),
        ),
    ]
