# Generated by Django 5.2.2 on 2025-09-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0006_alter_pnjinfos_prefered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjinfos',
            name='last_learned',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Compétence apprise lors du dernier opus'),
        ),
    ]
