# Generated by Django 5.2.2 on 2025-09-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0007_alter_pjinfos_last_learned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pjinfos',
            name='objectives',
            field=models.TextField(blank=True, default='', verbose_name='Objectifs de jeu'),
        ),
    ]
