# Generated by Django 5.2.2 on 2025-09-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0008_alter_pjinfos_objectives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
