# Generated by Django 5.2.2 on 2025-09-27 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0010_opus_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='larp.faction'),
        ),
    ]
