# Generated by Django 5.2.2 on 2025-09-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0011_inscription_faction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
