# Generated by Django 5.2.2 on 2025-10-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0012_alter_inscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjinfos',
            name='bg_completed',
            field=models.BooleanField(default=False, verbose_name='Background complété'),
        ),
    ]
