# Generated by Django 5.2.2 on 2025-10-15 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0013_pjinfos_bg_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bgchoice',
            name='requisit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='larp.bgchoice', verbose_name='Prérequis'),
        ),
    ]
