# Generated by Django 5.2.2 on 2025-10-25 07:50

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0014_bgchoice_requisit'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bgstep',
            name='unique_bg_step_per_faction',
        ),
        migrations.AddConstraint(
            model_name='bgstep',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('step', 'faction'), name='unique_bg_step_per_faction'),
        ),
    ]
