# Generated by Django 5.2.2 on 2025-10-31 18:03

import larp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0015_remove_bgstep_unique_bg_step_per_faction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pjinfos',
            name='status',
            field=models.CharField(choices=[('UNLOCKED', 'En édition par le joueur'), ('PLAYER_VALIDATED', 'Attente de validation Orga'), ('ORGA_VALIDATED', 'Validé par Orga')], default='UNLOCKED', max_length=25),
        ),
        migrations.AddField(
            model_name='pnjinfos',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bgstep',
            name='step',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character_bg_choices',
            name='step',
            field=models.IntegerField(default=0),
        ),
    ]
