# Generated by Django 5.2.2 on 2025-11-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0016_pjinfos_status_pnjinfos_completed_alter_bgstep_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='larp',
            name='pnjv_orga_contact',
            field=models.TextField(blank=True, default='', verbose_name='Info de contact orga des PNJV'),
        ),
    ]
