# Generated by Django 5.2.2 on 2025-11-06 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0017_larp_pnjv_orga_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bgchoice',
            name='short_name',
            field=models.CharField(max_length=80, verbose_name='Choix'),
        ),
        migrations.AlterField(
            model_name='bgstep',
            name='short_name',
            field=models.CharField(max_length=80, verbose_name='Étape'),
        ),
        migrations.CreateModel(
            name='PjDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nom du document')),
                ('document_url', models.URLField(verbose_name='URL')),
                ('pj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='larp.pjinfos', verbose_name='Personnage')),
            ],
        ),
    ]
