# Generated by Django 5.2.2 on 2025-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('larp', '0018_alter_bgchoice_short_name_alter_bgstep_short_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='larp',
            name='sheet_creation_opened',
            field=models.BooleanField(default=False, verbose_name='Création de personnage ouverte'),
        ),
    ]
