# Generated by Django 5.2.2 on 2025-06-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_frontend', '0002_migrate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPluginModel',
            fields=[
            ],
            options={
                'verbose_name': 'Ticket Plugin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
