# Generated by Django 5.2.2 on 2025-08-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_frontend', '0002_migrate_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundLinkPluginModel',
            fields=[
            ],
            options={
                'verbose_name': 'Background link plugin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
        migrations.CreateModel(
            name='BackgroundMenuPluginModel',
            fields=[
            ],
            options={
                'verbose_name': 'Menu image Plugin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('djangocms_frontend.frontenduiitem',),
        ),
    ]
